apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: postgres-policy
  namespace: weather-app
spec:
  endpointSelector:
    matchLabels:
      app: postgre-database
  ingress:
  - fromEndpoints:
    - matchLabels:
        app: weatherapp
    toPorts:
    - ports:
      - port: "5432"
        protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: weatherapp-policy
  namespace: weather-app
spec: 
  endpointSelector:
    matchLabels:
      app: weatherapp
  ingress:
  - fromCIDR:
    - 172.0.0.28/32
    - 172.0.0.51/32
    toPorts:
    - ports:
      - port: "5000"
        protocol: TCP
  egress:
  - toEntities:
    - all
  - toEndpoints:
    - matchLabels:
        k8s-app: kube-dns
      matchExpressions:
        - key: io.kubernetes.pod.namespace
          operator: In
          values:
            - kube-system
    toPorts:
      - ports:
          - port: "53"
            protocol: UDP
          - port: "53"
            protocol: TCP